#!/bin/sh
exec make "SPECIAL=" \
        "OPT=-O2" \
        "MACH=-Dlinux -D_FILE_OFFSET_BITS=64 -L/usr/X11R6/lib -I/usr/include/X11 -DNOSTEREO" \
        ARCH=IBMPC "COMPAT=strlcpy.o" \
        INSTDIR=/usr/local/bin \
        LIBDIR=/usr/local/lib/ray \
        ESUFFIX= \
        CC=gcc "$@" -f Rmakefile